{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-length": "107",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"",
    "sec-ch-ua-mobile": "?0",
    "authorization": "123",
    "content-type": "application/json",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    "sec-ch-ua-platform": "\"Windows\"",
    "client_secret": "123",
    "client_id": "123",
    "accept": "*/*",
    "origin": "http://localhost:8081",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "jenkins-timestamper-offset=-19800000; jenkins-timestamper=system; jenkins-timestamper-local=true"
  },
  "clientCertificate": null,
  "method": "PUT",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/customers/1007/orders/11",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/customers/1007/orders/11",
  "listenerPath": "/api/*",
  "relativePath": "/api/customers/1007/orders/11",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {
    "orderid": "11",
    "customerid": "1007"
  },
  "rawRequestUri": "/api/customers/1007/orders/11",
  "rawRequestPath": "/api/customers/1007/orders/11",
  "remoteAddress": "/127.0.0.1:55952",
  "requestPath": "/api/customers/1007/orders/11"
}