[
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "13",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "13",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "12",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "12",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "1",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "1",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "1",
    "Customer_ID": "1008",
    "ORDER_ID": "10",
    "PRODUCT_NAME": "Smart Slim Micro Stripe Shirt"
  },
  {
    "shipping_price": "10",
    "total": "110",
    "ORDER_ITEMS_ID": "2",
    "QUANTITY": "1",
    "subtotal": "100",
    "PRICE": "50",
    "PRODUCT_ID": "2",
    "Customer_ID": "1008",
    "ORDER_ID": "10",
    "PRODUCT_NAME": "Men's Regular Fit V-Neck Knit Sweater"
  }
]